import type { priceTypeEnum } from "./schema.ts";

type PriceType = (typeof priceTypeEnum.enumValues)[number];

export interface LocationSeed {
    slug: string;
    name: string;
    addressLine1: string;
    city: string;
    province: string;
    postalCode: string;
    phoneE164: string;
    phoneDisplay: string;
    timezone: string;
    sortOrder: number;
}

export interface BarberSeed {
    slug: string;
    displayName: string;
    sortOrder: number;
}

export interface ServiceCategorySeed {
    slug: string;
    name: string;
    sortOrder: number;
}

export interface ServiceSeed {
    slug: string;
    categorySlug: string;
    name: string;
    durationMinutes: number;
    priceCents: number;
    priceType: PriceType;
    displayPrice: string;
    sortOrder: number;
    isFeatured: boolean;
}

export const locationSeeds: readonly LocationSeed[] = [
    {
        slug: "eglinton",
        name: "Leaside Fades Eglinton",
        addressLine1: "866 Eglinton Ave E",
        city: "East York",
        province: "ON",
        postalCode: "M4G 2L1",
        phoneE164: "+16473482200",
        phoneDisplay: "(647) 348-2200",
        timezone: "America/Toronto",
        sortOrder: 10,
    },
    {
        slug: "millwood",
        name: "Leaside Fades Millwood",
        addressLine1: "909 Millwood Rd",
        city: "East York",
        province: "ON",
        postalCode: "M4G 1X2",
        phoneE164: "+14374237898",
        phoneDisplay: "(437) 423-7898",
        timezone: "America/Toronto",
        sortOrder: 20,
    },
] as const;

export const businessHourSeeds = [
    { dayOfWeek: 0, openTime: "10:00", closeTime: "17:00" },
    { dayOfWeek: 1, openTime: "10:00", closeTime: "19:00" },
    { dayOfWeek: 2, openTime: "10:00", closeTime: "19:00" },
    { dayOfWeek: 3, openTime: "10:00", closeTime: "19:00" },
    { dayOfWeek: 4, openTime: "10:00", closeTime: "19:00" },
    { dayOfWeek: 5, openTime: "10:00", closeTime: "19:00" },
    { dayOfWeek: 6, openTime: "10:00", closeTime: "19:00" },
] as const;

export const barberSeeds: readonly BarberSeed[] = [
    { slug: "sam-to", displayName: "Sam To", sortOrder: 10 },
    { slug: "yogesh-kumar", displayName: "Yogesh Kumar", sortOrder: 20 },
    { slug: "laura-nguyen", displayName: "Laura Nguyen", sortOrder: 30 },
    { slug: "shayan-hussain", displayName: "Shayan Hussain", sortOrder: 40 },
] as const;

export const barberLocationSeeds = [
    { barberSlug: "sam-to", locationSlug: "eglinton" },
    { barberSlug: "laura-nguyen", locationSlug: "eglinton" },
    { barberSlug: "laura-nguyen", locationSlug: "millwood" },
    { barberSlug: "yogesh-kumar", locationSlug: "millwood" },
    { barberSlug: "shayan-hussain", locationSlug: "millwood" },
] as const;

export const serviceCategorySeeds: readonly ServiceCategorySeed[] = [
    { slug: "hair-styling-men", name: "Hair & Styling (Men)", sortOrder: 10 },
    { slug: "hair-styling-women", name: "Hair & Styling (Women)", sortOrder: 20 },
    { slug: "hair-styling-boys", name: "Hair & Styling (Boy 9 & Under)", sortOrder: 30 },
] as const;

export const serviceSeeds: readonly ServiceSeed[] = [
    {
        slug: "mens-cut",
        categorySlug: "hair-styling-men",
        name: "Men's Cut",
        durationMinutes: 30,
        priceCents: 3000,
        priceType: "fixed",
        displayPrice: "$30",
        sortOrder: 10,
        isFeatured: false,
    },
    {
        slug: "mens-long-haircut",
        categorySlug: "hair-styling-men",
        name: "Men's Long Haircut",
        durationMinutes: 30,
        priceCents: 3500,
        priceType: "fixed",
        displayPrice: "$35",
        sortOrder: 20,
        isFeatured: false,
    },
    {
        slug: "mens-fade",
        categorySlug: "hair-styling-men",
        name: "Men's Fade",
        durationMinutes: 30,
        priceCents: 3500,
        priceType: "fixed",
        displayPrice: "$35",
        sortOrder: 30,
        isFeatured: false,
    },
    {
        slug: "bald-fade",
        categorySlug: "hair-styling-men",
        name: "Bald Fade",
        durationMinutes: 45,
        priceCents: 4500,
        priceType: "fixed",
        displayPrice: "$45",
        sortOrder: 40,
        isFeatured: false,
    },
    {
        slug: "senior-citizens-cut",
        categorySlug: "hair-styling-men",
        name: "Senior Citizen's Cut",
        durationMinutes: 30,
        priceCents: 2800,
        priceType: "fixed",
        displayPrice: "$28",
        sortOrder: 50,
        isFeatured: false,
    },
    {
        slug: "mens-perm",
        categorySlug: "hair-styling-men",
        name: "Men's Perm",
        durationMinutes: 60,
        priceCents: 7500,
        priceType: "from",
        displayPrice: "from $75",
        sortOrder: 60,
        isFeatured: false,
    },
    {
        slug: "line-up",
        categorySlug: "hair-styling-men",
        name: "Line Up",
        durationMinutes: 15,
        priceCents: 1500,
        priceType: "fixed",
        displayPrice: "$15",
        sortOrder: 70,
        isFeatured: false,
    },
    {
        slug: "beard-trim",
        categorySlug: "hair-styling-men",
        name: "Beard Trim",
        durationMinutes: 15,
        priceCents: 1500,
        priceType: "fixed",
        displayPrice: "$15",
        sortOrder: 80,
        isFeatured: false,
    },
    {
        slug: "beard-trim-machine",
        categorySlug: "hair-styling-men",
        name: "Beard Trim (Machine)",
        durationMinutes: 15,
        priceCents: 2500,
        priceType: "fixed",
        displayPrice: "$25",
        sortOrder: 90,
        isFeatured: false,
    },
    {
        slug: "hot-lather-shave",
        categorySlug: "hair-styling-men",
        name: "Hot Lather Shave",
        durationMinutes: 45,
        priceCents: 5500,
        priceType: "fixed",
        displayPrice: "$55",
        sortOrder: 100,
        isFeatured: false,
    },
    {
        slug: "hot-lather-head-shave",
        categorySlug: "hair-styling-men",
        name: "Hot Lather Head Shave",
        durationMinutes: 45,
        priceCents: 5500,
        priceType: "fixed",
        displayPrice: "$55",
        sortOrder: 110,
        isFeatured: false,
    },
    {
        slug: "mens-wash-style",
        categorySlug: "hair-styling-men",
        name: "Men's Wash & Style",
        durationMinutes: 15,
        priceCents: 1500,
        priceType: "fixed",
        displayPrice: "$15",
        sortOrder: 120,
        isFeatured: false,
    },
    {
        slug: "mens-wash-cut",
        categorySlug: "hair-styling-men",
        name: "Men's Wash & Cut",
        durationMinutes: 30,
        priceCents: 3500,
        priceType: "from",
        displayPrice: "from $35",
        sortOrder: 130,
        isFeatured: false,
    },
    {
        slug: "mens-wash-fade",
        categorySlug: "hair-styling-men",
        name: "Men's Wash & Fade",
        durationMinutes: 30,
        priceCents: 4000,
        priceType: "fixed",
        displayPrice: "$40",
        sortOrder: 140,
        isFeatured: false,
    },
    {
        slug: "mens-scalp-massage-20min",
        categorySlug: "hair-styling-men",
        name: "Men's Scalp Massage 20min",
        durationMinutes: 30,
        priceCents: 5000,
        priceType: "from",
        displayPrice: "from $50",
        sortOrder: 150,
        isFeatured: false,
    },
    {
        slug: "womens-medium-haircut-blowdry",
        categorySlug: "hair-styling-women",
        name: "Women's Medium Haircut & Blowdry",
        durationMinutes: 30,
        priceCents: 5500,
        priceType: "from",
        displayPrice: "from $55",
        sortOrder: 210,
        isFeatured: false,
    },
    {
        slug: "womens-medium-haircut-wash",
        categorySlug: "hair-styling-women",
        name: "Women's Medium Haircut & Wash",
        durationMinutes: 45,
        priceCents: 6500,
        priceType: "from",
        displayPrice: "from $65",
        sortOrder: 220,
        isFeatured: false,
    },
    {
        slug: "womens-medium-haircut-wash-blowdry",
        categorySlug: "hair-styling-women",
        name: "Women's Medium Haircut & Wash & Blowdry",
        durationMinutes: 45,
        priceCents: 7500,
        priceType: "from",
        displayPrice: "from $75",
        sortOrder: 230,
        isFeatured: false,
    },
    {
        slug: "womens-medium-haircut",
        categorySlug: "hair-styling-women",
        name: "Women's Medium Haircut",
        durationMinutes: 30,
        priceCents: 5500,
        priceType: "from",
        displayPrice: "from $55",
        sortOrder: 240,
        isFeatured: false,
    },
    {
        slug: "womens-short-haircut-wash",
        categorySlug: "hair-styling-women",
        name: "Women's Short Haircut & Wash",
        durationMinutes: 30,
        priceCents: 5500,
        priceType: "from",
        displayPrice: "from $55",
        sortOrder: 250,
        isFeatured: false,
    },
    {
        slug: "womens-short-haircut",
        categorySlug: "hair-styling-women",
        name: "Women's Short Haircut",
        durationMinutes: 30,
        priceCents: 4500,
        priceType: "from",
        displayPrice: "from $45",
        sortOrder: 260,
        isFeatured: false,
    },
    {
        slug: "womens-wash-blowdry",
        categorySlug: "hair-styling-women",
        name: "Women's Wash & Blowdry",
        durationMinutes: 30,
        priceCents: 3500,
        priceType: "from",
        displayPrice: "from $35",
        sortOrder: 270,
        isFeatured: false,
    },
    {
        slug: "womens-color",
        categorySlug: "hair-styling-women",
        name: "Women's Color",
        durationMinutes: 60,
        priceCents: 8000,
        priceType: "from",
        displayPrice: "from $80",
        sortOrder: 280,
        isFeatured: false,
    },
    {
        slug: "womens-root-touchup",
        categorySlug: "hair-styling-women",
        name: "Women's Root Touchup",
        durationMinutes: 30,
        priceCents: 6500,
        priceType: "from",
        displayPrice: "from $65",
        sortOrder: 290,
        isFeatured: false,
    },
    {
        slug: "womens-hair-wash",
        categorySlug: "hair-styling-women",
        name: "Women's Hair Wash",
        durationMinutes: 15,
        priceCents: 1500,
        priceType: "from",
        displayPrice: "from $15",
        sortOrder: 300,
        isFeatured: false,
    },
    {
        slug: "half-head-highlights",
        categorySlug: "hair-styling-women",
        name: "Half Head Highlights",
        durationMinutes: 90,
        priceCents: 9500,
        priceType: "from",
        displayPrice: "from $95",
        sortOrder: 310,
        isFeatured: false,
    },
    {
        slug: "full-head-highlights",
        categorySlug: "hair-styling-women",
        name: "Full Head Highlights",
        durationMinutes: 90,
        priceCents: 15000,
        priceType: "from",
        displayPrice: "from $150",
        sortOrder: 320,
        isFeatured: false,
    },
    {
        slug: "single-pack-highlights",
        categorySlug: "hair-styling-women",
        name: "Single Pack Highlights",
        durationMinutes: 15,
        priceCents: 1500,
        priceType: "fixed",
        displayPrice: "$15",
        sortOrder: 330,
        isFeatured: false,
    },
    {
        slug: "eight-pack-highlights",
        categorySlug: "hair-styling-women",
        name: "Eight Pack Highlights",
        durationMinutes: 45,
        priceCents: 5500,
        priceType: "from",
        displayPrice: "from $55",
        sortOrder: 340,
        isFeatured: false,
    },
    {
        slug: "boys-cut-wash-under-9",
        categorySlug: "hair-styling-boys",
        name: "Boy's Cut & Wash (Under 9)",
        durationMinutes: 30,
        priceCents: 3000,
        priceType: "fixed",
        displayPrice: "$30",
        sortOrder: 410,
        isFeatured: false,
    },
    {
        slug: "boys-cut-wash-10-over",
        categorySlug: "hair-styling-boys",
        name: "Boy's Cut & Wash (10 & Over)",
        durationMinutes: 30,
        priceCents: 3500,
        priceType: "fixed",
        displayPrice: "$35",
        sortOrder: 420,
        isFeatured: false,
    },
    {
        slug: "boys-fade-wash-10-over",
        categorySlug: "hair-styling-boys",
        name: "Boy's Fade & Wash (10 & Over)",
        durationMinutes: 30,
        priceCents: 4000,
        priceType: "fixed",
        displayPrice: "$40",
        sortOrder: 430,
        isFeatured: false,
    },
    {
        slug: "boys-fade-wash-under-9",
        categorySlug: "hair-styling-boys",
        name: "Boy's Fade & Wash (Under 9)",
        durationMinutes: 30,
        priceCents: 3500,
        priceType: "fixed",
        displayPrice: "$35",
        sortOrder: 440,
        isFeatured: false,
    },
    {
        slug: "boy-fade-10-over",
        categorySlug: "hair-styling-boys",
        name: "Boy Fade (10 & Over)",
        durationMinutes: 30,
        priceCents: 3500,
        priceType: "fixed",
        displayPrice: "$35",
        sortOrder: 450,
        isFeatured: false,
    },
    {
        slug: "boy-haircut-10-over",
        categorySlug: "hair-styling-boys",
        name: "Boy Haircut (10 & Over)",
        durationMinutes: 30,
        priceCents: 3000,
        priceType: "fixed",
        displayPrice: "$30",
        sortOrder: 460,
        isFeatured: false,
    },
    {
        slug: "boys-fade-under-9",
        categorySlug: "hair-styling-boys",
        name: "Boy's Fade (Under 9)",
        durationMinutes: 30,
        priceCents: 3000,
        priceType: "fixed",
        displayPrice: "$30",
        sortOrder: 470,
        isFeatured: false,
    },
    {
        slug: "boys-cut-under-9",
        categorySlug: "hair-styling-boys",
        name: "Boy's Cut (Under 9)",
        durationMinutes: 30,
        priceCents: 2500,
        priceType: "fixed",
        displayPrice: "$25",
        sortOrder: 480,
        isFeatured: false,
    },
] as const;
